services:
  frontend:
    image: dhruv2k3/basal-frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - basal-net
networks:
  basal-net:
    driver: bridge